name: <%= ARGV[-1] %>
root: .
windows:
  - <%= ARGV[-1] %>:
      layout: 61c5,318x91,0,0{217x91,0,0,0,100x91,218,0[100x34,218,0,1,100x33,218,35,2,100x22,218,69,3]}
      panes:
        - nix-shell --command 'clear; fish -C "nvim"' || nvim
        - nix-shell --command 'clear; fish -C "git status"' || git status
        - nix-shell --command 'clear; fish' || clear
        - nix-shell --command 'clear; fish' || clear

